# Generated by Django 4.2 on 2026-07-02 17:26

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0003_alter_autor_table_alter_eixotecnologia_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='eixotecnologia',
            options={'verbose_name': 'Eixo de Tecnologia', 'verbose_name_plural': 'Eixos de Tecnologia'},
        ),
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='eixotecnologia',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem título', max_length=200, verbose_name='Título')),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('publicada', models.BooleanField(default=False)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='B', max_length=1, verbose_name='Nível')),
                ('texto', tinymce.models.HTMLField(verbose_name='Texto')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('id_fk_autor', models.ForeignKey(db_column='id_fk_autor', on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='motorartigos.autor', verbose_name='Autor')),
                ('id_fk_eixo', models.ForeignKey(db_column='id_fk_eixo', on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='motorartigos.eixotecnologia', verbose_name='Eixo')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'db_table': 'artigo',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
