# Generated by Django 4.2 on 2026-07-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0004_alter_autor_options_alter_eixotecnologia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/', verbose_name='Foto de Capa'),
        ),
    ]
