# Generated by Django 4.1 on 2026-06-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0005_alter_artigo_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='id_fk_autor',
            field=models.ForeignKey(db_column='id_fk_autor', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='id_fk_eixo',
            field=models.ForeignKey(db_column='id_fk_eixo', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.eixotecnologia', verbose_name='Eixo tecnológico'),
        ),
    ]
